#!/bin/sh

if [ "$1" = "dual1" ]; then
	xrandr --output LVDS1 --primary --mode 1366x768 --left-of HDMI1 --output HDMI1 --mode 1440x900
fi

if [ "$1" = "dual2" ]; then
	xrandr --output LVDS1 --primary --mode 1366x768 --left-of HDMI1 --output HDMI1 --mode 1366x768
fi

if [ "$1" = "monitor" ]; then
	xrandr --output LVDS1 --off --output HDMI1 --auto
fi

if [ "$1" = "tv" ]; then
	xrandr --output LVDS1 --off --output HDMI1 --auto
fi

if [ "$1" = "laptop" ]; then
	xrandr --output LVDS1 --auto --output HDMI1 --off
fi
